# site settings
title: MORAX PHOTOGRAPHY by
subtitle: Airylight web Development
email: moraxphotos@gmail.com
description: I'm a French Londoner for 5 years now and my studio are located in
  Shoreditch.<br />I take amazing headshots for corporate and creative poepole in
  London.
baseurl: "/morax-beta" # the subpath of your site, e.g. /blog
url: https://ismaelsane.github.io
author:
street_address: 1234 Somewhere Road
city: LONDON
state: UK
zip_code: 55555
country: United Kingdom
phone: +447 956 457 889

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/Morax-photography-2260675220845739
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/moraxphotography/
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/supermorax

# build settings
markdown: kramdown

sass:
  style: compressed
